-- Seed data for MediSwift

-- Insert medicines
INSERT INTO public.medicines (
  name, 
  brand, 
  price, 
  discount_price, 
  rating, 
  category, 
  quantity, 
  image, 
  description, 
  usage, 
  side_effects, 
  contraindications, 
  stock
) VALUES
(
  'Paracetamol 500mg', 
  'Generic', 
  35, 
  30, 
  4.8, 
  'Pain Relief', 
  '10 tablets', 
  '/Paracetamol.webp', 
  'Paracetamol is used to treat headaches, muscle aches, arthritis, backache, toothaches, colds, and fevers.', 
  'Take 1-2 tablets every 4-6 hours as needed. Do not exceed 8 tablets in 24 hours.', 
  'Rare side effects may include nausea, stomach pain, and rash. Seek medical attention if experiencing severe side effects.', 
  'Do not use if allergic to paracetamol. Consult doctor if you have liver disease, kidney disease, or consume alcohol regularly.', 
  50
),
(
  'Amoxicillin 500mg', 
  'Generic', 
  84, 
  75, 
  4.7, 
  'Antibiotics', 
  '10 capsules', 
  '/Amoxicillin.webp', 
  'Amoxicillin is a penicillin antibiotic that fights bacteria in the body. It is used to treat bacterial infections such as bronchitis and pneumonia.', 
  'Take as directed by your doctor, usually every 8 or 12 hours with or without food. Complete the full course even if you feel better.', 
  'Side effects may include diarrhea, stomach upset, or allergic reactions. Contact your doctor if experiencing severe rash, persistent diarrhea, or difficulty breathing.', 
  'Do not use if allergic to penicillin antibiotics. Inform your doctor about your medical history, especially of kidney disease.', 
  35
),
(
  'Azithromycin 500mg', 
  'Generic', 
  90, 
  80, 
  4.7, 
  'Antibiotics', 
  '3 tablets', 
  '/Azithromycin.webp', 
  'Azithromycin is an antibiotic that fights bacteria. It''s used to treat a wide variety of bacterial infections.', 
  'Take one tablet daily, with or without food. Complete the full course prescribed by your doctor.', 
  'Common side effects include diarrhea, nausea, abdominal pain, and vomiting.', 
  'Do not use if you have a history of allergic reactions to azithromycin or similar antibiotics.', 
  20
),
(
  'Ciprofloxacin 500mg', 
  'Generic', 
  70, 
  65, 
  4.5, 
  'Antibiotics', 
  '10 tablets', 
  '/Ciprofloxacin.webp', 
  'Ciprofloxacin is a fluoroquinolone antibiotic used to treat bacterial infections.', 
  'Take one tablet twice daily, with or without food, as directed by your doctor.', 
  'May cause tendon damage, nervous system effects, and other serious side effects.', 
  'Not recommended for those with a history of tendon disorders related to fluoroquinolone use.', 
  25
),
(
  'Metformin 500mg', 
  'Generic', 
  25, 
  22, 
  4.6, 
  'Diabetes', 
  '10 tablets', 
  '/Metformin.webp', 
  'Metformin is used to control blood sugar levels in people with type 2 diabetes.', 
  'Take with meals to minimize stomach upset. Follow your doctor''s instructions carefully.', 
  'May cause stomach upset, diarrhea, and metallic taste which usually improve with time.', 
  'Not suitable for those with severe kidney disease or metabolic acidosis.', 
  40
),
(
  'Amlodipine 5mg', 
  'Generic', 
  15, 
  12, 
  4.8, 
  'Cardiac', 
  '10 tablets', 
  '/Amlodipine.webp', 
  'Amlodipine is a calcium channel blocker used to treat high blood pressure and angina.', 
  'Take once daily with or without food at the same time each day.', 
  'May cause swelling in ankles or feet, dizziness, and flushing.', 
  'Inform your doctor if you have liver disease or severe heart problems.', 
  55
),
(
  'Atorvastatin 10mg', 
  'Generic', 
  55, 
  48, 
  4.7, 
  'Cardiac', 
  '10 tablets', 
  '/Atorvastatin.webp', 
  'Atorvastatin is used to lower cholesterol and reduce the risk of heart disease.', 
  'Take once daily, with or without food, preferably in the evening.', 
  'May cause muscle pain, weakness, and liver enzyme abnormalities.', 
  'Not suitable for pregnant women or those with active liver disease.', 
  30
),
(
  'Omeprazole 20mg', 
  'Generic', 
  20, 
  18, 
  4.7, 
  'Gastro', 
  '10 capsules', 
  '/Omeprazole.webp', 
  'Omeprazole reduces stomach acid production and treats conditions like GERD and peptic ulcers.', 
  'Take before meals, typically once daily in the morning.', 
  'May cause headache, abdominal pain, and nausea.', 
  'Inform your doctor if you''re taking other medications as interactions may occur.', 
  45
),
(
  'Pantoprazole 40mg', 
  'Generic', 
  40, 
  35, 
  4.6, 
  'Gastro', 
  '10 tablets', 
  '/Pantoprazole.webp', 
  'Pantoprazole is a proton pump inhibitor that reduces stomach acid production.', 
  'Take once daily, with or without food. Swallow whole with water.', 
  'May cause headache, diarrhea, and stomach pain.', 
  'Inform your doctor of all medications you take to avoid potential interactions.', 
  38
);

-- Insert doctors
INSERT INTO public.doctors (
  name, 
  specialty, 
  experience, 
  rating, 
  review_count, 
  consultation_fee, 
  available_today, 
  available_for_video, 
  available_for_in_clinic, 
  next_available, 
  image, 
  hospital, 
  location, 
  education, 
  languages, 
  available_slots
) VALUES
(
  'Dr. Anil Sharma', 
  'General Physician', 
  '12 years', 
  4.5, 
  150, 
  800, 
  true, 
  true, 
  true, 
  'Today, 2:30 PM', 
  'https://randomuser.me/api/portraits/men/65.jpg', 
  'MediCare Hospital', 
  'Mumbai, Maharashtra', 
  'MBBS - General Medicine', 
  ARRAY['English', 'Hindi'], 
  '{"2023-08-25": ["09:00", "10:00", "11:00", "14:00", "15:00", "16:00"]}'::jsonb
),
(
  'Dr. Priya Patel', 
  'Cardiologist', 
  '15 years', 
  4.8, 
  220, 
  1200, 
  false, 
  true, 
  true, 
  'Tomorrow, 10:00 AM', 
  'https://randomuser.me/api/portraits/women/65.jpg', 
  'Heart Care Center', 
  'Delhi, Delhi', 
  'MD - Cardiology, MBBS', 
  ARRAY['English', 'Hindi', 'Gujarati'], 
  '{"2023-08-26": ["10:00", "11:00", "12:00", "15:00", "16:00", "17:00"]}'::jsonb
),
(
  'Dr. Rajesh Kumar', 
  'Dermatologist', 
  '8 years', 
  4.3, 
  95, 
  900, 
  true, 
  true, 
  false, 
  'Today, 4:00 PM', 
  'https://randomuser.me/api/portraits/men/32.jpg', 
  'Skin Solutions Clinic', 
  'Bangalore, Karnataka', 
  'MD - Dermatology, MBBS', 
  ARRAY['English', 'Hindi', 'Kannada'], 
  '{"2023-08-25": ["11:00", "12:00", "16:00", "17:00"]}'::jsonb
),
(
  'Dr. Sneha Reddy', 
  'Gynecologist', 
  '10 years', 
  4.7, 
  180, 
  1000, 
  false, 
  true, 
  true, 
  'Aug 27, 9:30 AM', 
  'https://randomuser.me/api/portraits/women/33.jpg', 
  'Women\'s Health Hospital', 
  'Hyderabad, Telangana', 
  'MS - Obstetrics & Gynecology, MBBS', 
  ARRAY['English', 'Hindi', 'Telugu'], 
  '{"2023-08-27": ["09:30", "10:30", "11:30", "14:30", "15:30", "16:30"]}'::jsonb
),
(
  'Dr. Vikram Singh', 
  'Orthopedic Surgeon', 
  '20 years', 
  4.9, 
  300, 
  1500, 
  true, 
  false, 
  true, 
  'Today, 6:00 PM', 
  'https://randomuser.me/api/portraits/men/45.jpg', 
  'Bone & Joint Institute', 
  'Chennai, Tamil Nadu', 
  'MS - Orthopedics, MBBS', 
  ARRAY['English', 'Hindi', 'Tamil'], 
  '{"2023-08-25": ["10:00", "12:00", "14:00", "18:00"]}'::jsonb
),
(
  'Dr. Ananya Das', 
  'Pediatrician', 
  '12 years', 
  4.6, 
  210, 
  850, 
  true, 
  true, 
  true, 
  'Today, 3:00 PM', 
  'https://randomuser.me/api/portraits/women/28.jpg', 
  'Children\'s Medical Center', 
  'Kolkata, West Bengal', 
  'MD - Pediatrics, MBBS', 
  ARRAY['English', 'Hindi', 'Bengali'], 
  '{"2023-08-25": ["09:00", "10:00", "12:00", "15:00", "16:00"]}'::jsonb
); 