// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qzfcczdsyrmqoryyawyf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF6ZmNjemRzeXJtcW9yeXlhd3lmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIyMDU5MDUsImV4cCI6MjA1Nzc4MTkwNX0.JcWgAi7TAPlGF_4wS43DJ7ElKmtdY8rcYtxqBBrOLws";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);